### ISSUE TITLE
Error using tensorRT-LLM as backend

### ISSUE THREAD

**Issue by Wyswyss** [shashikg/WhisperS2T#61]
Hi, I've encountered an error when using tensorRT-LLM as backend. Here're my steps.
First I installed latest whisperS2T using `pip install -U git+https://github.com/shashikg/WhisperS2T.git` in an existng docker container of nvidia's TensorRT with tags `nvcr.io/nvidia/tensorrt:24.04-py3` and tensorRT-LLM version 0.10.0.dev2024043000.
Then I installed ffmpeg.
Then I tried to transcribe my audio file using 
```
import whisper_s2t

model = whisper_s2t.load_model(model_identifier="large-v2", backend='TensorRT-LLM',asr_options={'without_timestamp': False})

files = ['/workspace/2cf4b4ae9aaa699b0d3e945b8d1a861f.mp3']
lang_codes = ['en']
tasks = ['transcribe']
initial_prompts = [None]

out = model.transcribe_with_vad(files,
                                lang_codes=lang_codes,
                                tasks=tasks,
                                initial_prompts=initial_prompts,
                                batch_size=24)

print(out) # Print first utterance for first file
```

The logs are as follows:
```root@058e96add7ae:/workspace# python example.py
[TensorRT-LLM] TensorRT-LLM version: 0.10.0.dev2024043000
'trt_build_args' not provided in model_kwargs, using default configs.
100%|█████████████████████████████████████| 2.10M/2.10M [00:01<00:00, 1.66MiB/s]
100%|█████████████████████████████████████| 2.87G/2.87G [01:06<00:00, 46.3MiB/s]
⠹ Exporting Model To TensorRT Engine (3-6 mins) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0:00:01Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/whisper_s2t/backends/tensorrt/engine_builder/builder.py", line 29, in <module>
    from tensorrt_llm.models import quantize_model
ImportError: cannot import name 'quantize_model' from 'tensorrt_llm.models' (/usr/local/lib/python3.10/dist-packages/tensorrt_llm/models/__init__.py)
⠹ Exporting Model To TensorRT Engine (3-6 mins) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0:00:02
Traceback (most recent call last):
  File "/workspace/example.py", line 4, in <module>
    model = whisper_s2t.load_model(model_identifier="large-v2", backend='TensorRT-LLM',asr_options={'without_timestamp': False})
  File "/usr/local/lib/python3.10/dist-packages/whisper_s2t/__init__.py", line 44, in load_model
    return WhisperModel(model_identifier, **model_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/whisper_s2t/backends/tensorrt/model.py", line 108, in __init__
    self.model = WhisperTRT(self.model_path)
  File "/usr/local/lib/python3.10/dist-packages/whisper_s2t/backends/tensorrt/trt_model.py", line 168, in __init__
    self.encoder = WhisperEncoding(engine_dir)
  File "/usr/local/lib/python3.10/dist-packages/whisper_s2t/backends/tensorrt/trt_model.py", line 16, in __init__
    self.session = self.get_session(engine_dir)
  File "/usr/local/lib/python3.10/dist-packages/whisper_s2t/backends/tensorrt/trt_model.py", line 20, in get_session
    with open(config_path, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/whisper_s2t/models/trt/large-v2/c55664fdf5b447062c4cd7a0b64b72fc/encoder_config.json'
```
I've tried to figure out the cause. I think something was wrong in the building process of tensorRT-LLM. But I am not familiar with it. Could you please help me figure out the cause? Thanks!

**Comment by Wyswyss** [comment]
Nevermind, it seemed to be the difference between tensorRT-LLM version 0.8 and version 0.10, as in version 0.10, 'quantize_model' is no longer defined in tensorrt_llm.models. It worked fine when I tried the pre-built docker container.
